language: node_js
node_js:
- 8

sudo: required

os:
- osx

addons:
  chrome: stable

before_script:
- export DISPLAY=:99.0

before_deploy:
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

install:
- yarn install

cache:
  yarn: true

jobs:
  include:
#  - stage: test
#    script:
#    - yarn test
#    - ng lint
#  - stage: build
#    if: branch != master
#    script: yarn build
  - stage: build + deploy
#    if: branch = master
    os:
    - osx
    - windows
    - linux
    script: yarn electron:local
    deploy:
      provider: releases
      api_key: $ENCRYPTED_GITHUB_TOKEN
      file_glob: true
      file: release/*
