language: node_js
node_js:
  - 8
sudo: required
os:
  - windows
  - linux
  - osx
addons:
    chrome: stable
install:
  - npm set progress=false
  - npm install
jobs:
  include:
  - stage: test
    script:
      - ng lint
      - npm run test
  - stage: release
    script: npm run build
  - stage: deploy
    if: branch = master
    deploy:
      provider: releases

