language: node_js
node_js:
- 8

sudo: required

os:
- osx

addons:
  chrome: stable

before_script:
- export DISPLAY=:99.0

install:
- yarn install

cache:
  yarn: true

jobs:
  include:
  - stage: test
    script:
    - yarn test
    - ng lint
  - stage: build
    if: branch != master
    script: yarn build
  - stage: build + deploy
    if: branch = master
    os:
    - osx
    - windows
    - linux
    script: yarn build
    deploy:
      provider: releases
