language: node_js
node_js:
- 8

sudo: required

os:
- windows
- linux
- osx

addons:
  chrome: stable

before_script:
- export DISPLAY=:99.0

install:
- yarn install

cache:
  yarn: true

jobs:
  include:
  - stage: test
    if: os = linux
    script:
      - ng lint
      - yarn test
  - stage: build
    if: branch != master
    script: yarn build
  - stage: build + deploy
    if: branch = master
    script: yarn build
    deploy:
      provider: releases
